name: Format and test Python library

on:
  push:
    branches: 
      - "main"

jobs:
  format:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Format with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: ./py
          args: "format"

      - name: Fix with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: ./py
          args: "check --fix"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          src: ./py
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        working-directory: py
        run: uv python install 3.14

      - name: Sort imports with isort 
        run: uv run isort py

  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          src: ./py
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        working-directory: py
        run: uv python install 3.14

      - name: Test with pytest
        working-directory: py
        run: uv run -m pytest
